### ISSUE TITLE
Element doesn't exist

### ISSUE THREAD

**Issue by GertJanArts** [aex351/home-assistant-neerslag-card#37]
![image](https://user-images.githubusercontent.com/20320533/225462388-8992098b-442d-4e99-b9ff-89c5f3423b17.png)
Not the first time... Tried everything many times: restart, clear browser cache, uninstall/install, install neerslag app etc etc 
Something is wrong with this lovelace, but I cannot figure out what
Current version: 2022.07.08.0

**Comment by aex351** [comment]
Thanks for the report. While this error can occur in various situations. In this case there seems to be a problem with an external dependency that is hosted on `unpkg.com`  /  using `Cloudflare.com`. Without this dependency the `neerslag-card` can not load.

I am seeing Cloudflare error 520 in the console logs https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-520-web-server-returns-an-unknown-error

The problem is external. To fix this problem there are a couple of options:

- Wait till the external dependency is fixed;
- Change the external dependency to another CDN;
- Remove the external dependency and embed it within the `neerslag-card`. 

Option 2 could be a quick fix . Option 3 would be the best as it will remove external dependencies. See also: https://github.com/aex351/home-assistant-neerslag-app/issues/40

Note: to make it clear, this is not an issue with your local installation. Do not spend time on reinstalling/restarting/etc. As it will not resolve this specific issue.

**Comment by GertJanArts** [comment]
Hi thanks for your answer, but does your answer match my question? I'm not mensioniing the details in you answer :)

**Comment by aex351** [comment]
Yes, it does. It explains why you were experiencing the issue and what can be done to resolve it. 

In any case, the external dependency with `unpkg.com` has been fixed, so the root cause of this error should be resolved and you should no longer see this error message.

**Comment by GertJanArts** [comment]
mmm... great that you still see the problem without a real error message :) Problem seems to be solved now. I can add the neerslag-card again.
Thanks for your good work!

**Comment by caro7372** [comment]
New version doesn't seem to see the neerslag-card.
If I install an older one it works again.

<img width="406" alt="Scherm­afbeelding 2023-04-04 om 19 25 33" src="https://user-images.githubusercontent.com/63898040/229980769-bbbf0267-4eb3-4d1a-89be-278db5871c7b.png">

<img width="467" alt="Scherm­afbeelding 2023-04-04 om 19 30 01" src="https://user-images.githubusercontent.com/63898040/229980825-1c1b3fe9-c046-43cd-b3a0-1ec74321c32f.png">

**Comment by Janoz-NL** [comment]
I have the same issue, but only in safari on the iPad or in the companion app on the iPad. Android works, chrome works, safari on a macbook works.

**Comment by pvmil** [comment]
I am a happy user of the card, I just started using IOS companion app as of today (moving from an android tablet to an IOS 12.5.7 iPad,) and experience the same issue "Custom element doesn't exist: neerslag-card". Hope there's a way to fix this, can I provide additional information?

**Comment by ebbenberg** [comment]
Newest HA update 2024.4.2 also broke the card.

**Comment by aex351** [comment]
There is an issue with unpkg, for which there is a dependency. It is unrelated to Home Assistant or the latest update. Will continue to look in to this.

**Comment by aex351** [comment]
unpkg seems to be up and running again. Issue has been resolved.

**Comment by thoompje** [comment]
> I have the same issue, but only in safari on the iPad or in the companion app on the iPad. Android works, chrome works, safari on a macbook works.

Same issue here...

**Comment by svenvdmeer** [comment]
This happens to me a lot.

**Comment by Soulfly999** [comment]
Me.too, I have to refresh my Dashboards all the time.

**Comment by thoompje** [comment]
Any updates on this thread? Still need to refresh, sometimes its loaded correctly and most of the times not... Really frustrating. @aex351 anything we can do on this to get this working correctly?

**Comment by WouterJN** [comment]
I also have this problem all the time, anyone found the source of the issue?

**Comment by mhoogenbosch** [comment]
Still an issue.

**Comment by HenriMatthijssen** [comment]
Still an issue. Does anyone has a workaround for this?

**Comment by Woutch** [comment]
Same here :-(

If I can do anything to help or double check, let me know.

**Comment by Phyxsius7** [comment]
This error happens sporadicly. Not sure why, but it works for several hours and then I get this message.

<img width="1514" height="519" alt="Image" src="https://github.com/user-attachments/assets/5a091262-3d1f-452d-ab8f-48f04b6f4859" />

**Comment by aex351** [comment]
Are you using just the `neerslag-card` or the `neerslag-app`?

**Comment by svde** [comment]
This request is returning a 404:

`"GET /hacsfiles/home-assistant-neerslag-card/neerslag-card.dist.js?hacstag=342944383202412280 HTTP/2.0" 404`

**Comment by Phyxsius7** [comment]
> Are you using just the `neerslag-card` or the `neerslag-app`?

I have both installed.
Removed both and did cler cache and reboot between every step.
Seems to be resolved
